name: "Generate pcb production data"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - 'hardware/pcb/*'
      - 'hardware/pcb/Makefile'
      - '.github/workflows/pcb.yml'
  pull_request:
    paths:
      - 'hardware/pcb/*'
      - 'hardware/pcb/Makefile'
      - '.github/workflows/pcb.yml'

jobs:

  GenPCB:
    name: PCB fabrication files
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
    # needs: [ERC, DRC]

    steps:
    - uses: actions/checkout@v2
    
    - name: Insert github hash and date
      shell: bash
      run: |
        sed -i "s/GITHASH/$(echo ${GITHUB_SHA} | cut -c1-8)/" hardware/pcb/24-clocks.kicad_pcb && \
        sed -i "s/GITDATE/$(date +%d-%m-%Y)/" hardware/pcb/24-clocks.kicad_pcb && \
        sed -i "s/GITHASH/$(echo ${GITHUB_SHA} | cut -c1-8)/" hardware/pcb/*.sch && \
        sed -i "s/GITDATE/$(date +%d-%m-%Y)/" hardware/pcb/*.sch

    - name: Generate PCB files
      run: |
        cd hardware/pcb && make pcb_main pcba_master pcba_slave

    - name: Retrieve results
      uses: actions/upload-artifact@v1
      with:
        name: 24_clocks_pcb_data
        path: output
