name: "Generate pcb production data"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - 'hardware/pcb/*'
      - 'hardware/pcb/Makefile'
      - '.github/workflows/pcb.yml'
  pull_request:
    paths:
      - 'hardware/pcb/*'
      - 'hardware/pcb/Makefile'
      - '.github/workflows/pcb.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # ERC:
  #   runs-on: ubuntu-latest
  #   container: setsoft/kicad_auto:10.4-5.1.6rc

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Run ERC
  #     run: |
  #       cd hardware/pcb && make erc

  #   - name: Retrieve results
  #     uses: actions/upload-artifact@v1
  #     with:
  #       name: ERC_Output
  #       path: hardware/pcb/Generated

  # DRC:
  #   runs-on: ubuntu-latest
  #   container: setsoft/kicad_auto:10.4-5.1.6rc
  #   needs: ERC

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Run DRC
  #     run: |
  #       cd hardware/pcb && make drc

  #   - name: Retrieve results
  #     uses: actions/upload-artifact@v1
  #     with:
  #       name: DRC_Output
  #       path: hardware/pcb/Generated

  FabSch:
    name: Schematic fabrication files
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:10.4-5.1.6rc
    # needs: [ERC, DRC]

    steps:
    - uses: actions/checkout@v2
    
    - name: Insert github hash and date
      shell: bash
      run: |
        sed -i "s/GITHASH/$(echo ${GITHUB_SHA} | cut -c1-8)/" hardware/pcb/24-clocks.kicad_pcb && \
        sed -i "s/GITDATE/$(date +%d-%m-%Y)/" hardware/pcb/24-clocks.kicad_pcb && \
        sed -i "s/GITHASH/$(echo ${GITHUB_SHA} | cut -c1-8)/" hardware/pcb/*.sch && \
        sed -i "s/GITDATE/$(date +%d-%m-%Y)/" hardware/pcb/*.sch

    - name: Run schematic stuff
      run: |
        cd hardware/pcb && make drc pcb_main pcba_master pcba_slave

    - name: Retrieve results
      uses: actions/upload-artifact@v1
      with:
        name: 24_clocks_pcb_data
        path: output
